### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 1251480932** [yafuly/SyntacticGen#1]
Dear GitHub author,
Would it be possible for you to make your dataset publicly available? Also, could you provide some guidance on how to create a dataset if I wish to process my own data?

**Comment by yafuly** [comment]
Hi,

The original data for the paper was removed due to a system transfer. 

For guidance on dataset creation, you can consider the following steps:

1. Parse the target-side texts using an off-the-shelf parser, e.g., [Berkeley Parser](https://github.com/nikitakit/self-attentive-parser).
2. Traverse the constituency parsing tree in a layer-wise order to obtain the constituents and their corresponding infilling texts at each tree level.
3. Construct the syntax contexts and the infilling texts accordingly given the results of step 2 (See paper for details).

We provide a sample dataset in [toy_data](https://github.com/yafuly/SyntacticGen/tree/main/toy_data). Specifically, the "training" directory contains the source texts, target texts and parsing results (step 1), whereas the "training_triplets" directory contains the final sequence-to-sequence syntax-aware data for training (step 3).
